name: ED
markdown: kramdown
markdown_ext:  md
pygments: true
baseurl: 
url:         http://localhost:4000
exclude: [bower_components, Gemfile, Gemfile.lock, sass, '*.json', '*.rb', Gruntfile.js, README.md, node_modules ]
